In [1]:
import pandas as pd

In [25]:
data = {
    'hours': [8, 11, 9, 5, 7.5, 9.5, 10, 7, 9, 9.5, 8, 10.5, 9, 6.5, 9],
    'score': [56,70, 51, 24, 30, 66, 48, 36, 42, 61, 39, 87, 73, 48, 46]
}

In [26]:
df = pd.DataFrame(data)

In [27]:
df

    hours  score
0     8.0     56
1    11.0     70
2     9.0     51
3     5.0     24
4     7.5     30
5     9.5     66
6    10.0     48
7     7.0     36
8     9.0     42
9     9.5     61
10    8.0     39
11   10.5     87
12    9.0     73
13    6.5     48
14    9.0     46

In [28]:
df.head()

   hours  score
0    8.0     56
1   11.0     70
2    9.0     51
3    5.0     24
4    7.5     30

In [29]:
y = df.score.values

In [30]:
x = df.hours.values

In [31]:
y_pred = 8 * x - 15

In [32]:
x

array([ 8. , 11. ,  9. ,  5. ,  7.5,  9.5, 10. ,  7. ,  9. ,  9.5,  8. ,
       10.5,  9. ,  6.5,  9. ])

In [33]:
y

array([56, 70, 51, 24, 30, 66, 48, 36, 42, 61, 39, 87, 73, 48, 46])

In [34]:
y_pred

array([49., 73., 57., 25., 45., 61., 65., 41., 57., 61., 49., 69., 57.,
       37., 57.])

In [38]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y,y_pred)
mae

9.333333333333334

In [39]:
from sklearn.metrics import mean_squared_error
mse = mearn_squared_error(y,y_pred)
mse

NameError: name 'mearn_squared_error' is not defined